// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
// If you change the class to 'public' in order to use it outside its assembly
//  you should also change the fields from 'const' to 'public static readonly'

namespace Rantiy.FontIconsInCode;

static class CustomFontIcons
{
    public const string icon_home = "\ue800";
    public const string icon_left_arrow = "\ue801";
    public const string icon_shopping_cart_solid = "\ue802";
    public const string icon_favorite_solid = "\ue803";
    public const string icon_favorite_outline = "\ue804";
    public const string icon_add_shopping_cart_outline = "\ue805";
    public const string icon_delete = "\ue806";
    public const string icon_no_image_available = "\ue807";
    public const string icon_brand = "\ue808";
}
